localization:
  zh-CN:
    name: Makefile
    description: Makefile 是一个构建工具
  en-US:
    name: Makefile
    description: Makefile is a build tool
path: makefile
articles:
  install:
    path: install
    localization:
      zh-CN:
        title: 安装 Makefile
      en-US:
        title: Install Makefile
